hell
# https://nushell.sh

# Paths
path = [
  '/home/robert/configuration/bin'
]

# Options
skip_welcome_message = true

# Starship
# https://starship.rs
prompt = 'starship prompt'

# Startup
startup = [

  # Aliases
  alias @ = fork
  alias p = echo
  alias _ = rm -rf
  alias md = mkdir

  # NixOS
  # https://nixos.org
  alias nix-update = sudo nixos-rebuild switch
  alias nix-upgrade = sudo nixos-rebuild switch --upgrade --keep-going --fallback
  alias nix-gc = sudo nix-collect-garbage --delete-old

  # Sleep
#  alias z = sudo systemctl suspend
#  alias zz = swaymsg exit
#  alias zzz = sudo shutdown now

  # procs
  # https://github.com/dalance/procs
  alias ps = procs

  # htop
  # https://htop.dev
  alias top = htop

  # rm
  alias rm = rm -rf --trash
  alias rm! = rm -rf ~/.local/share/Trash

  # bat
  # https://github.com/sharkdp/bat
  alias cat = bat

  # fd
  # https://github.com/sharkdp/fd
  alias find = fd

  # ripgrep
  # https://github.com/BurntSushi/ripgrep
  alias grep = rg

  # Git
  # https://git-scm.com
  alias g = git

  # Change the working directory to the Git root:
  def @cd [] {
    cd $(git rev-parse --show-toplevel | str trim)
  }

  # gitui
  # https://github.com/extrawurst/gitui
  alias G = gitui

  # Broot
  # https://dystroy.org/broot/
  def br [...rest] {
    let path = $(broot --out /dev/stdout $rest | str trim)
    let is_empty = $(= $path | empty?)
    if $is_empty {} {
      cd $path
    }
  }
  alias . = br .

  # exa
  # https://the.exa.website
  alias l = exa --icons
  alias la = exa --icons --all
  alias ll = exa --icons --git --long
  alias lla = exa --icons --git --long --all
  alias T = exa --tree
  alias ta = exa --tree --all

  # Web browser
  alias b = fork google-chrome-stable

]


